import type { UseFormReturn } from "react-hook-form";
import { z } from "zod";

import { createProjectClientSchema } from "@wildfires-org/turboplan-workspace/types";

// Two creation modes share this form:
// - Research mode (default): name is auto-generated by AI after prompt
//   validation, so we omit it from the form and require the prompt.
// - Bring-your-own-project mode (`hasExistingProject`): the AI research phase is
//   skipped, so the user types the name directly and the prompt is optional.
// `createProjectClientSchema` keeps `prompt` optional at the shape level, so we
// re-add an optional `name` and enforce the "required unless" rule with a local
// `.superRefine` (valid here because `.omit()`/`.extend()` return ZodObject).
export const dialogSchema = createProjectClientSchema
  .omit({ name: true })
  .extend({
    name: z
      .string()
      .max(100, "Name must be less than 100 characters")
      .optional(),
  })
  .superRefine((data, ctx) => {
    if (data.hasExistingProject) {
      if (!data.name || data.name.trim().length === 0) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          message: "Project name is required",
          path: ["name"],
        });
      }
      return;
    }

    if (!data.prompt || data.prompt.trim().length === 0) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Project setup prompt is required",
        path: ["prompt"],
      });
    }
  });

export type DialogFormInput = z.input<typeof dialogSchema>;
export type DialogFormData = z.infer<typeof dialogSchema>;
export type DialogForm = UseFormReturn<
  DialogFormInput,
  unknown,
  DialogFormData
>;

export const PROMPT_SUGGESTIONS = [
  {
    label: "📄 USFS Fuel Break CE",
    name: "USFS Fuel Break CE",
    prompt:
      "I'm a NEPA planner at Umatilla NF, and I'm working on the P52 fuel break which will put a 2500-acre fuel break into WUI at Heppner Ranger District.",
  },
  {
    label: "📚 USFS Veg EA",
    name: "USFS Veg EA",
    prompt:
      "I'm a silviculturist at Rogue River-Siskiyou NF, preparing an EA for the 1,200-acre Jackson Creek vegetation restoration project to reduce fuels and restore late-successional habitat.",
  },
  {
    label: "🌲 BLM Road Repair",
    name: "BLM Road Repair",
    prompt:
      "I'm a project lead in Utah, managing the reconstruction of a 5-mile segment of the popular Moab Slickrock Trail damaged by erosion.",
  },
];
