import { loader } from "fumadocs-core/source";

import { docs } from "@/.source";

// Page tree + page lookup for the /docs route. `docs` is generated by
// fumadocs-mdx into the root `.source/` dir from `content/docs`.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
